\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{thesis}[2025/03/21 Custom Thesis Class]

% Default: 12pt Times New Roman
\LoadClass[12pt]{article}

\RequirePackage{graphicx}  % For including images
\RequirePackage{fancyhdr}  % For custom headers/footers
\RequirePackage{geometry}  % For margins
\RequirePackage{titlesec}  % For section title customization
\RequirePackage{datetime}  % For date formatting
\RequirePackage{setspace}  % For line spacing
\RequirePackage[backend=biber,style=numeric]{biblatex}

\setstretch{1.25}  % Set line spacing to 1.25
\addbibresource{references.bib}

% Set margins
\geometry{a4paper, left=2.5cm, right=2.5cm, top=3cm, bottom=3cm}

% Set date format to DD mmmm YYYY
\newdateformat{customdate}{\THEDAY~\monthname[\THEMONTH]~\THEYEAR}

% Define custom commands
\newcommand{\subtitle}[1]{\gdef\@subtitle{#1}}
\newcommand{\subject}[1]{\gdef\@subject{#1}}
\newcommand{\affiliation}[1]{\gdef\@affiliation{#1}}
\newcommand{\supervisor}[1]{\gdef\@supervisor{#1}}
\newcommand{\supervisorAffiliation}[1]{\gdef\@supervisorAffiliation{#1}}

% Default values for warnings
\def\@subtitle{\@latex@warning@no@line{No \noexpand\subtitle given}}
\def\@supervisor{\@latex@warning@no@line{No \noexpand\supervisor given}}
\def\@affiliation{\@latex@warning@no@line{No \noexpand\affiliation given}}

% Define the title page
\def\maketitle{
    \begin{titlepage}
        % \hfill \includegraphics[clip,scale=.35]{thi_AImotion.png}
        \vspace*{6ex}
        \begin{center}
            {\LARGE \textsc{Technische Hochschule Ingolstadt}} \\[4ex]
            {\Large Faculty of Computer Science \\}
        \end{center}
        \vspace*{3ex}
        \begin{center}
            {\Huge \textbf{~\\ \@title} \\}
        \end{center}
        \vspace*{8ex}
        \begin{center}
            {\huge \textsc{\@subtitle} \\[3ex] }
            {\Large \@author  \\}
        \end{center}
        \vspace*{15ex}
        \begin{center}
            {\large
            \begin{tabular}{ r l }
                Supervisor: & \@supervisor \\ 
                Date: & \customdate\today
            \end{tabular}
            }
        \end{center}	
    \end{titlepage}
}
% Header & Footer
\lhead{\@title}
\renewcommand{\footrulewidth}{0.4pt}
\rfoot{\thepage}
\lfoot{\@author}
\cfoot{\nouppercase{\rightmark}}


% Setup Header & Footer
\pagestyle{fancy}
\fancyhf{}  % Clear all default header/footer settings
\fancyhead[L]{\textbf{\@title}}  % Left header: Title
\fancyhead[R]{}  % Right header: Page number
\renewcommand{\headrulewidth}{0.4pt}  % Horizontal line under header

% Footer Configuration
\renewcommand{\footrulewidth}{0.4pt}
\fancyfoot[L]{\@author}  % Bottom left: Author Name
\fancyfoot[C]{\nouppercase{\rightmark}}  % Bottom center: Section title
\fancyfoot[R]{\thepage}  % Bottom right: Page number




\endinput
